language: java

before_install:
  - chmod +x gradlew

jdk:
  - oraclejdk13

cache:
  directories:
  - "$HOME/.gradle"

notifications:
  email: false

addons:
  sonarcloud:
    organization: "f4k0"
    token:
      secure: $SONAR_TOKEN

script:
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY